apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-staging-pod
spec:
  selector:
    matchLabels:
      app: api-staging-pod
  template:
    metadata:
      labels:
        app: api-staging-pod
    spec:
      containers:
      - image: gcr.io/lyrical-link-271413/springboot:latest
        name: api-staging-pod
        ports:
          - containerPort: 8080