apiVersion: v1
kind: Service
metadata:
  name: api-staging-service
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: api-staging-pod
  sessionAffinity: None
  type: LoadBalancer