apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
spec:
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
      - image: gcr.io/lyrical-link-271413/springboot:latest
        name: api
        ports:
          - containerPort: 8080