apiVersion: v1
kind: Service
metadata:
  name: api-staging-service
spec:
  type: ClusterIP
  ports:
    - name: "http-port"
      protocol: "TCP"
      port: 8080
      targetPort: 8080
  sessionAffinity: None
  selector:
    app: api-staging-pod