apiVersion: v1
kind: ConfigMap
metadata:
  creationTimestamp: 2016-02-18T18:52:05Z
  name: nginx-config
  resourceVersion: "516"
  uid: b4952dc3-d670-11e5-8cd0-68f728db1985
data:
    nginx.conf.template: |
        events {
            worker_connections  16;
        }
        http {
            server {
                listen 80;
                server_name ${SERVER_NAME};
                location /api {
                    proxy_pass http://api-staging-service:8080/;
                }
                location / {
                    proxy_pass http://web-staging-service:80/;
                }
            }
        }