apiVersion: v1
kind: Service
metadata:
  name: nginx-staging-service
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: nginx-staging-pod
  sessionAffinity: None
  type: LoadBalancer
  loadBalancerIP: "34.84.30.35"