apiVersion: v1
kind: Service
metadata:
  name: web-staging-service
spec:
  type: ClusterIP
  ports:
    - name: "http-port"
      protocol: "TCP"
      port: 80
      targetPort: 80
  sessionAffinity: None
  selector:
    app: web-staging-pod